In [7]:
import numpy as np
import pandas as pd
from random import randint,seed
from tqdm import tqdm
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,MinMaxScaler 

In [27]:
def create_traindata():
    list_random=[]
    counter=0
    while counter < 20000:
        while(True):
            #seed(counter+1)
            h = randint(1,448)
            w = randint(1,448)
            c = randint(1,1280)
            n = randint(1,1024)
            f = randint(1,min(11,min(h,w)))
            s = randint(1,4)
            if not ([h,w,c,n,f,s] in list_random):
                break
        list_random.append([h,w,c,n,f,s])
        counter+=1
    return list_random         
def create_traindata2():
    list_random=[]
    counter=0
    
    H = list(int(2*1.6**p) for p in range(1,13))
    W = list(int(2*1.6**p) for p in range(1,13))
    C = list(int(2*1.6**p) for p in range(1,15))
    N = list(int(2*1.6**p) for p in range(1,15))
    print len(H)*len(W)*len(C)*len(N)*2*5
    for h in H:
        for w in W:
            for c in C:
                for n in N:
                    for f in range(2,min(11,min(h,w)),2):
                        for s in range(1,3):
                            list_random.append([h,w,c,n,f,s]) 
    return list_random         

In [40]:
C = list(int(2*1.6**p) for p in range(1,15))
C

[3, 5, 8, 13, 20, 33, 53, 85, 137, 219, 351, 562, 900, 1441]

In [29]:
train_data = create_traindata2()

282240


In [30]:
len(train_data)

206584

In [31]:
train_data_arr = np.asarray(train_data,dtype=np.int32)

In [32]:
train_data_arr[0:1000].shape

(1000, 6)

In [33]:
"""
np.savetxt("train_input_1.csv",train_data_arr[0:5000],delimiter=',',fmt='%i')
np.savetxt("train_input_2.csv",train_data_arr[5000:10000],delimiter=',',fmt='%i')
np.savetxt("train_input_3.csv",train_data_arr[10000:15000],delimiter=',',fmt='%i')
np.savetxt("train_input_4.csv",train_data_arr[15000:20000],delimiter=',',fmt='%i')
"""

'\nnp.savetxt("train_input_1.csv",train_data_arr[0:5000],delimiter=\',\',fmt=\'%i\')\nnp.savetxt("train_input_2.csv",train_data_arr[5000:10000],delimiter=\',\',fmt=\'%i\')\nnp.savetxt("train_input_3.csv",train_data_arr[10000:15000],delimiter=\',\',fmt=\'%i\')\nnp.savetxt("train_input_4.csv",train_data_arr[15000:20000],delimiter=\',\',fmt=\'%i\')\n'

In [34]:
np.random.shuffle(train_data_arr)

In [35]:
print train_data_arr

[[ 562   20  900   85    4    2]
 [  33   53    8    3    2    1]
 [  33   53   13   20   10    1]
 ...
 [  33   20   53  219    4    2]
 [  85   85 1441   20    6    2]
 [  20  137   33    3    4    1]]


In [36]:
sub_arr = np.split(train_data_arr,4)

In [37]:
sub_arr

[array([[562,  20, 900,  85,   4,   2],
        [ 33,  53,   8,   3,   2,   1],
        [ 33,  53,  13,  20,  10,   1],
        ...,
        [ 53,  13, 137,  53,   4,   1],
        [  5,  53, 219, 900,   4,   1],
        [ 33, 562, 900,  20,   2,   2]], dtype=int32),
 array([[  5,  13, 562, 219,   4,   2],
        [  5,   8,  85,  53,   2,   2],
        [ 53, 562, 351, 137,   8,   1],
        ...,
        [ 13, 137,   8,  13,   8,   2],
        [ 20,  33,   5,  20,  10,   1],
        [351, 562,   5,   3,   8,   1]], dtype=int32),
 array([[  8, 219,  33,   3,   6,   1],
        [562, 351,  53, 219,   8,   1],
        [137,  20,   3,  20,   4,   2],
        ...,
        [351,   5,  53, 219,   4,   2],
        [ 33,  85, 219,   5,   2,   1],
        [219, 562, 137, 219,   8,   2]], dtype=int32),
 array([[  53,  562,    8,   53,    2,    1],
        [  85,   13,   13,  219,    4,    1],
        [  33,   53,    3,    5,    8,    1],
        ...,
        [  33,   20,   53,  219,    4,    2],

In [38]:
np.save("chunk1",sub_arr[0])
np.save("chunk2",sub_arr[1])
np.save("chunk3",sub_arr[2])
np.save("chunk4",sub_arr[3])

In [39]:
print sub_arr[0]

[[562  20 900  85   4   2]
 [ 33  53   8   3   2   1]
 [ 33  53  13  20  10   1]
 ...
 [ 53  13 137  53   4   1]
 [  5  53 219 900   4   1]
 [ 33 562 900  20   2   2]]


In [21]:
sub_arr[0].shape

(33614, 6)

In [22]:
a

NameError: name 'a' is not defined

In [23]:
a[np.argsort(a)]

NameError: name 'a' is not defined